# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

# Example:
# Input:
# s = "abcd"
# t = "abcde"
# Output:
# e
# Explanation:
# 'e' is the letter that was added.


from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        counts = Counter(s)
        for c in t:
            if c not in counts or counts[c] == 0:
                return str(c)
            counts[c] -= 1
        return ''


solution = Solution()
s = "abcd"
t = "abcde"
print(solution.findTheDifference(s, t))
